const GOOGLE_CALENDAR_CLIENT_ID = "374390014624-ij9beaqcc05glfp5te4gvdaitc4tefck.apps.googleusercontent.com";
const GOOGLE_CALENDAR_SECRET = "mRUbdaEPXHRPpLB8XMbj5mR3";

module.exports.GOOGLE_CALENDAR_CLIENT_ID = GOOGLE_CALENDAR_CLIENT_ID;
module.exports.GOOGLE_CALENDAR_SECRET = GOOGLE_CALENDAR_SECRET;